name: 'RedTideRegion'
version: '1.3.0'
main: alairack.region.Region
api-version: '1.20'
authors: [alairack]
depend:
  - WorldEdit
  - WorldGuard
softdepend: [Multiverse-Core]

commands:
  ar:
    description: 管理员的领地操作
    usage: "用法: /<command> [create|addOwner|addMember|nbt]"
    permission: region.create
    permission-message: 你没有编辑领地的权限！
  addOwner:
    description: 添加另一位玩家成为自己领地的主人
    usage: "用法: /<command> 领地编号 玩家名称 "
    permission: region.addOwner
    permission-message: 你没有执行此命令的权限！

permissions:
  region.create:
    description: 领地权限
    default: op
  region.addOwner:
    description: 添加另一位玩家成为自己领地的主人权限
    default: true